AllCops:
  NewCops: disable
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/{console, setup}'
    - 'Rakefile'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
